name: Build request
description: Запросить автоматическую сборку проекта
title: "[BUILD]"
labels: [build]
body:
  - type: input
    id: confirm
    attributes:
      label: Подтвердите запуск сборки
      description: Введите любое слово, чтобы подтвердить запуск сборки
      placeholder: ok
    validations:
      required: true
